In [4]:
!pip install keras #>instalasi keras library
import keras #>memanggil library keras
import numpy as np #>memanggil library numpy
from sklearn.datasets import load_iris #>inisialisasi iris dari sklearn dataset dan memanggil iris
dataset=load_iris() #> fungsi load dataset iris dari proses sebelumnya
print (dataset) #> mencetak isi dataset

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6,

In [5]:
print(type(dataset)) #> mencetak tipe dataset
print(len(dataset)) #> mencetak panjang dataset
print(dataset.keys()) 
print(dataset['data'][0:5])
print(dataset['target'][0:5])
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names'])
print(dataset['filename'])
x=dataset['data']
print(len(x))
y=dataset['target']
print(len(y))
print(x[0])
print(y[0])

<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [6]:
from keras.utils import to_categorical
Ny=len(np.unique(y))
print(Ny)
Y=to_categorical(y,num_classes=Ny)
print(y[0:5])

3
[0 0 0 0 0]


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])

[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [6.2 2.9 4.3 1.3]
 [6.1 2.6 5.6 1.4]
 [5.4 3.4 1.7 0.2]]
[[5.4 3.4 1.5 0.4]
 [5.9 3.  4.2 1.5]
 [6.2 3.4 5.4 2.3]
 [7.2 3.  5.8 1.6]
 [7.2 3.2 6.  1.8]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [8]:
from sklearn.preprocessing import StandardScaler
import numpy as np
scaler=StandardScaler()
scaler.fit(x_train)

X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))

[2.56209288 2.76162366 1.81961335 1.73006694]
[-1.85970094 -2.42624621 -1.56982078 -1.43862547]


In [9]:
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu'))

keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense(20, activation='relu'))


model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                100       
                                                                 
 dense_1 (Dense)             (None, 20)                420       
                                                                 
 dense_2 (Dense)             (None, 20)                420       
                                                                 
 dense_3 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(X_train, y_train, epochs=195, batch_size=80,validation_split=0.1)

Epoch 1/195
2/2 [==============================] - 1s 278ms/step - loss: 1.2830 - accuracy: 0.1570 - val_loss: 1.2517 - val_accuracy: 0.2143
Epoch 2/195
2/2 [==============================] - 0s 35ms/step - loss: 1.2408 - accuracy: 0.1653 - val_loss: 1.2038 - val_accuracy: 0.2143
Epoch 3/195
2/2 [==============================] - 0s 35ms/step - loss: 1.2020 - accuracy: 0.1983 - val_loss: 1.1578 - val_accuracy: 0.3571
Epoch 4/195
2/2 [==============================] - 0s 35ms/step - loss: 1.1647 - accuracy: 0.2231 - val_loss: 1.1148 - val_accuracy: 0.4286
Epoch 5/195
2/2 [==============================] - 0s 45ms/step - loss: 1.1291 - accuracy: 0.2562 - val_loss: 1.0739 - val_accuracy: 0.5714
Epoch 6/195
2/2 [==============================] - 0s 35ms/step - loss: 1.0959 - accuracy: 0.2810 - val_loss: 1.0348 - val_accuracy: 0.5714
Epoch 7/195
2/2 [==============================] - 0s 38ms/step - loss: 1.0636 - accuracy: 0.3554 - val_loss: 0.9980 - val_accuracy: 0.5714
Epoch 8/195
2/2 [==

In [12]:
print(model.evaluate(X_train, y_train))

5/5 [==============================] - 0s 3ms/step - loss: 0.0548 - accuracy: 0.9852
[0.054755259305238724, 0.9851852059364319]


In [16]:
testing=model.evaluate(X_test, y_test)
#print("\n%s: %.2f%%" % (model.evaluate[1]+'uracy of Model on testing data', testing[1]*100))

1/1 [==============================] - 0s 40ms/step - loss: 0.1844 - accuracy: 0.8667


In [17]:
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis=1)
Y_test = np.argmax(y_test, axis=1)
#to get confusion matrix
print(confusion_matrix(Y_test, predictions))
#to get values of all evalution metrics
print(classification_report(Y_test, predictions))

1/1 [==============================] - 0s 154ms/step
[[5 0 0]
 [0 4 1]
 [0 1 4]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.80      0.80      0.80         5
           2       0.80      0.80      0.80         5

    accuracy                           0.87        15
   macro avg       0.87      0.87      0.87        15
weighted avg       0.87      0.87      0.87        15

